version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - ./prometheus-sample.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    restart: on-failure
    depends_on:
      - server

  server:
    build:
      context: .
    command:
      - server
    ports:
      - "127.0.0.1:3100:3100"

  speedtest:
    build:
      context: .
    command:
      - speedtest
      - --server
      - "http://server:3100"
    restart: "no"
    depends_on:
      - server
