{
 "title": "Speedtest",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"speedtest\", __name__=\"speedtest_ping_latency\"}"
    }
   ]
  },
  {
   "title": "Download bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"speedtest\", __name__=\"speedtest_download_bandwidth\"} / 125000"
    }
   ]
  },
  {
   "title": "Upload bandwidth",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"speedtest\", __name__=\"speedtest_upload_bandwidth\"}/125000"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "{job=\"speedtest\", __name__=\"speedtest_download_bandwidth\"} / 125000",
     "legendFormat": "download"
    },
    {
     "expr": "{job=\"speedtest\", __name__=\"speedtest_upload_bandwidth\"} / 125000",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{job=\"speedtest\", __name__=\"speedtest_ping_latency\"}",
     "legendFormat": "latency"
    }
   ]
  }
 ]
}