apiVersion: v1
kind: ServiceAccount
metadata:
  name: speedtest-prometheus-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: speedtest-prometheus-exporter
    app.kubernetes.io/part-of: speedtest-prometheus-exporter
    app.kubernetes.io/managed-by: kubectl
