apiVersion: v1
kind: Service
metadata:
  name: speedtest-prometheus-exporter-external
  namespace: monitoring
  labels:
    app.kubernetes.io/name: speedtest-prometheus-exporter-external
    app.kubernetes.io/part-of: speedtest-prometheus-exporter
    app.kubernetes.io/managed-by: kubectl
spec:
  type: LoadBalancer
  ports:
    - port: 21216
      targetPort: 3100
      protocol: TCP
  selector:
    app.kubernetes.io/name: speedtest-prometheus-exporter
    app.kubernetes.io/part-of: speedtest-prometheus-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-prometheus-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: speedtest-prometheus-exporter
    app.kubernetes.io/part-of: speedtest-prometheus-exporter
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app.kubernetes.io/name: speedtest-prometheus-exporter
    app.kubernetes.io/part-of: speedtest-prometheus-exporter
